sonar.organization=brianegge
sonar.projectKey=brianegge_homeassistant-magewell
sonar.sources=custom_components/magewell
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
